version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB_NAME
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    #    ports:
    #      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongodb:
    container_name: mongodb
    image: mongo:4
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

  #  mongo-express:
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    environment:
  #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: portfolioapp
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_HOSTNAME: mysqldb
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mysqldb
      - mongodb
    stdin_open: true
    tty: true


volumes:
  db-config:
  db-data:
  mongodb-data:
